const fs = require('fs');

const appFile = 'c:/Users/USER/Desktop/Fort-space/fortefrontend/src/App.jsx';
let content = fs.readFileSync(appFile, 'utf8');

const missing = [
  "AvailabilitySchedulingPage.jsx",
  "CreateGigPage.jsx",
  "FeaturedGigShowcasePage.jsx",
  "FreelancerBoostProfilePage.jsx",
  "FreelancerDeliveryPage.jsx",
  "FreelancerDisputeHistoryPage.jsx",
  "FreelancerLearningPage.jsx",
  "FreelancerPerformanceInsightsPage.jsx",
  "FreelancerPortfolioPage.jsx",
  "FreelancerSubscriptionsPage.jsx",
  "FreelancerSuccessScorePage.jsx",
  "FreelancerWalletDashboard.jsx",
  "GigAnalyticsDashboard.jsx",
  "GigCategoryPage.jsx",
  "GigDeliveryPage.jsx",
  "GigDescriptionFaqPage.jsx",
  "GigDuplicatePage.jsx",
  "GigGalleryUploadPage.jsx",
  "GigOrderTrackingPage.jsx",
  "GigPerformanceInsightsPage.jsx",
  "GigPreviewPage.jsx",
  "GigPricingPage.jsx",
  "GigPublishSuccessPage.jsx",
  "GigRequirementsPage.jsx",
  "GigRequirementsSubmissionPage.jsx",
  "GigSearchPage.jsx",
  "GigsPage.jsx",
  "GigTitleSeoPage.jsx",
  "GigVideoUploadPage.jsx",
  "JobInvitationsPage.jsx",
  "MilestonesPage.jsx",
  "NotificationsPage.jsx",
  "ProposalAnalyticsPage.jsx",
  "RankingDashboard.jsx",
  "SkillsCertificationsPage.jsx",
  "TrendingGigsPage.jsx",
  "WithdrawalsPage.jsx"
];

let imports = '';
let routes = '';

missing.forEach(file => {
  const componentName = file.replace('.jsx', '');
  imports += `import ${componentName} from './freelancer/pages/${componentName}';\n`;
  
  // Create a kebab-case path
  let kebabPath = componentName
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .toLowerCase();
  
  // if it starts with freelancer-, strip it for the route (or keep it under /freelancer)
  kebabPath = kebabPath.replace(/^freelancer-/, '');
  kebabPath = kebabPath.replace(/-page$/, '');
  
  // For gig-related things
  if (kebabPath.startsWith('gig-')) {
    kebabPath = 'gigs/' + kebabPath.replace(/^gig-/, '');
  }
  
  routes += `        <Route path="/freelancer/${kebabPath}" element={<FreelancerProtectedRoute><FreelancerLayout><${componentName} /></FreelancerLayout></FreelancerProtectedRoute>} />\n`;
});

// Insert imports right before "const RoleProtectedRoute"
const importAnchor = "const RoleProtectedRoute = ";
if (content.includes(importAnchor)) {
    content = content.replace(importAnchor, `// Autogenerated Freelancer Imports\n${imports}\n${importAnchor}`);
} else {
    console.error("Could not find import anchor.");
}

// Insert routes right before "</Routes>"
const routeAnchor = "</Routes>";
if (content.includes(routeAnchor)) {
    content = content.replace(routeAnchor, `        {/* Autogenerated Freelancer Routes */}\n${routes}\n      ${routeAnchor}`);
} else {
    console.error("Could not find route anchor.");
}

fs.writeFileSync(appFile, content, 'utf8');
console.log("Updated App.jsx successfully!");
